= Inversion of Control and Dependency Injection: Summary and Recommended Practices

== Summary

* _Inversion of Control_ is the design technique where a class receives its dependencies instead of creating them.
** _Dependencies_ are the external types that a class needs to perform its function.
** _Inversion of Control_ provides more flexibility in how classes are used, because the usage context can decide which concrete dependencies to use.
*** E.g. Use different concrete dependencies on an application usage or on a unit test usage.
** This flexibility is made possible if the dependencies are defined as interfaces and not as concrete (i.e. non-abstract) classes.

* _Dependency Injection_ is the act of providing the dependencies to the class instance that needs them.
** _Constructor Injection_ happens when those dependencies are provided as constructor arguments.
** _Property Injection_ happens when those dependencies are provided by assigning properties to them, after the _dependant_ instance is created.

* _Dependency Injection Container_ is the _thing_ (e.g. class instance) that knows how to create instances and inject all the dependencies into them.
** The use of the inversion of control design principle does not require the use of a dependency injection container. Dependencies can be provided, i.e. injected, manually.

* _Dependency Graph_
** Consider type `A` that depends on types `B` and `C`.
** Types `B` and `C` can also have their own dependencies, for instance, types `D` and `E`, and types `F` and `G`, respectively.
** These types and their dependencies define a directed graph, where types (or instances) are the nodes and dependency relations are the edges.
** When using constructor injection
*** To construct an instance of `A` we need to construct instances of `B` and `C`.
*** However, to construct an instance of `B` we need to first construct instances of `D` and `E`.
*** And to construct an instance of `C` we need to first construct instances of `F` and `G`.
** Computing the construction order and calling the constructors can be done automatically by a container, based on the dependency graph, or can be made by explicitly written application code (i.e. non-automatically).

== Recommended Practices

* Components should use the inversion of control principle, however they should (mostly) *not depend* on a specific container or automatic dependency injection technology.    
** Why?
*** To enable unit testing without the need to use the container, i.e, by using _manual_ dependency injection.
*** To enable usage with different container technologies.
** What does this mean?
*** Avoid depending or using container specific types or functions.
*** An example is depending on the container itself.
** There are situations were it may be unavoidable to depend on the specific container technology. Always triple-check if that is the case.
** An example where we need to use container specific technology is in the use of the `@Component` annotation to include a class in the component scan procedure.

* Always prefer constructor injection instead of property injection.
** Why?
*** So that the component instance is immediately usable after construction, because it already has all the necessary dependencies.
*** So that the dependencies are immutable non-nullable references.
*** Note that when using property injection, there is a time interval where the instance is created but isn't yet usable because the dependencies haven't been provided to it yet. In addition, property injection requires the dependency fields to be mutable, with all the mutability consequences.

** Only use property injection when constructor injection is not possible. An example is on JUnit test classes, because the instance creation is done by JUnit and not the DI container. I.e., the container doesn't control the instance creation, so the injection needs to be done at a later stage.
